apiVersion: v1
kind: Service
metadata:
  name: hello-devops-service
  labels:
    app: hello-devops
spec:
  selector:
    app: hello-devops
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer